Install OpenMPI to its own conda environment

diff --git a/post_install b/post_install
--- a/post_install
+++ b/post_install
@@ -1,23 +1,31 @@
 #!/bin/bash
-
+#
 # This script automatically creates required code Nodes in AiiDA database,
 # based on the assumption that the codes are accessible locally.
+# It also install OpenMPI for parallel ORCA execution in a separate conda environment.
+
+set -euo pipefail
 
 # This needs to match the path where you mounted the code!
-# TODO: Perhaps we could autodetermine this via find?
+# TODO: Perhaps we should try to autodetermine this via find?
 if [[ -z ${ORCA_PATH-} ]]; then
   ORCA_PATH=/opt/orca
 fi
-if [[ ! -d "${ORCA_PATH}" || ! -f "${ORCA_PATH}"/orca ]];then
-  echo "WARNING: Could not find ORCA installation at \"${ORCA_PATH}\", you will need to create a code node on a remote computer."
-  exit 0
+
+### CREATE CONDA CHANNEL FOR OPENMPI ###
+if [[ -z ${OPENMPI_VERSION-} ]]; then
+  OPENMPI_VERSION=4.1.1
 fi
+CONDA_ENV_ORCA="orca"
+# TODO: Not sure if this variable is necessary anymore
+OPENMPI_LIB="~/.conda/envs/$CONDA_ENV_ORCA/lib"
 
+conda create --yes --override-channels -c conda-forge \
+  --name ${CONDA_ENV_ORCA} openmpi=${OPENMPI_VERSION}
 
-# We append LD_LIBRARY path since we install OpenMPI
-# via conda in ATMOSPEC Docker image
-# TODO: Detect when OpenMPI is not installed, and (somehow) disable running on multiple CPUs, because that will fail.
-OPENMPI_LIB=/opt/conda/lib
+PREPEND_TEXT="conda activate ${CONDA_ENV_ORCA};\
+  export PATH=${ORCA_PATH}:\$PATH;\
+  export LD_LIBRARY_PATH=${ORCA_PATH}:${OPENMPI_LIB}:\$LD_LIBRARY_PATH"
 
 function create_orca_code() {
     computer=$1
@@ -37,9 +45,14 @@ function create_orca_code() {
             --default-calc-job-plugin ${calcjob} \
             --computer ${computer} \
             --filepath-executable ${ORCA_PATH}/orca \
-            --prepend-text "export PATH=${ORCA_PATH}:\$PATH;export LD_LIBRARY_PATH=${ORCA_PATH}:${OPENMPI_LIB}:\$LD_LIBRARY_PATH" \
+            --prepend-text "${PREPEND_TEXT}" \
     )
 }
+
+if [[ ! -d "${ORCA_PATH}" || ! -f "${ORCA_PATH}"/orca ]];then
+  echo "WARNING: Could not find ORCA installation at \"${ORCA_PATH}\", you will need to create a code node on a remote computer."
+  exit 0
+fi
 
 # Create orca code node on computer localhost,
 # which is created by default in aiidalab Docker image
